# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20190505_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imei',
            field=models.CharField(max_length=64),
        ),
    ]
