# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20190505_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_password',
            field=models.CharField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
