# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20190505_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_password',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imei',
            field=models.CharField(max_length=64),
        ),
    ]
