# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20190505_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imei',
            field=models.CharField(default=1111, max_length=64),
            preserve_default=False,
        ),
    ]
